### ISSUE TITLE
Support mocking extern C bindings

### ISSUE THREAD

**Issue by chris-zen** [kriomant/mockers#11]
Do you think is it possible to mock C bindings with Rust ? I would like to test a library built on top of a C binding, and I need to check that certain calls are done with specific parameters, as well as to test that my wrapping code behaves as expected for different scenarios where the C bindings return different values.

**Comment by kriomant** [comment]
I can generate free functions instead of BlaBlaMock struct. You will need to link to mock library instead of original C one for testing.

**Comment by chris-zen** [comment]
@kriomant thanks for the response. I am not very familiarised with "mockers" so I didn't understand very well your answer. Do you have any source example or gist to exemplify this use case ?

**Comment by kriomant** [comment]
It is currently not possible to mock C functions. However, I can extend mockers so that, for example,

```rust
#[derive(GlobalMock)]
trait SomeCLib {
  fn foo(a: i32);
  fn bar(b: u16);
}
```

will be expanded into `foo` and `bar` free functions instead of `SomeCLibMock` struct. Then you will be able to set expectation for these global functions.
