### ISSUE TITLE
Traits with associated types

### ISSUE THREAD

**Issue by 3Hren** [kriomant/mockers#13]
Hi!

Is there a way to mock traits with associated types using this library?

**Comment by kriomant** [comment]
No, there isn't. But if you describe in details what you want I will try to implement it.

**Comment by 3Hren** [comment]
Something like this:

```rust
trait Factory {
    type Item;
    fn create(&self) -> Self::Item;
}

struct OtherMock;

let mut fact = scenario.create_mock::<Factory<Item=OtherMock>>();
scenario.expect(fact.create().and_return(OtherMock));
```

**Comment by 3Hren** [comment]
Also trying to compile something like this: 
```rust
#[derive(Mock)]
pub trait MockFactory: Factory<Item = MockBind> {}
```

results in ICE error because of [this](https://github.com/kriomant/mockers/blob/master/mockers_codegen/src/lib.in.rs#L50).

**Comment by 3Hren** [comment]
Also dealing with proc_macro results in `error: proc-macro derives may only be applied to struct/enum items` :(

**Comment by kriomant** [comment]
Putting all complaints into one issue is counterproductive, please create separate issues.

**Comment by 3Hren** [comment]
That won't help either. 

I'd like to discuss the possible solutions here and to find out whether this project is alive. And to help with it if so, since we're SUDDENLY from the same company, instead of reinventing the similar crate by myself.

**Comment by kriomant** [comment]
I'm on vacation right now, we'll continue discussion in just several days, when I return.

**Comment by kriomant** [comment]
AFAIK, `Factory<Item=Foo>` syntax can be used for type bounds, but not for generics instantiation, because associated types are not parameters.

**Comment by la10736** [comment]
Can be used to set the associated trait type:

```rust
use std::fmt::Debug;

trait Factory
    where Self::Item: Debug
{
    type Item;

    fn dump(item: &Self::Item) {
        println!("{:?}", item);
    }
}

trait StringFactory: Factory<Item=String> {}

impl Factory for String {
    type Item = Self;
}

impl StringFactory for String {}

fn main() {
    String::dump(&String::from("Hello word!"))
}
```

... Maybe there are simpler example but I hope it is clear enought.

**Comment by kriomant** [comment]
Support for associated types is added.
However, it isn't very useful without ability to create mocks and add expectations from within expectation reactions. I'm working on it.
