### ISSUE TITLE
Default implementation on mocks.

### ISSUE THREAD

**Issue by andoriyu** [kriomant/mockers#14]
Either I'm missing something or Derive method overrides a bit more than I want. 

Say I have:  
```
 #[derive(Mock)]
pub trait Engine {
    /// Get state of the current connection.
    fn connection_state(&self) -> ConnectionState;
    fn generate_session(&self) -> Session {
        Session::new(self.server_public_key(), self.our_long_term_keys())
    }

    /// Make a call. This call verify that connection is in the right state.
    fn call(&self, req: Frame) -> FutureResponse {
        if self.connection_state() == ConnectionState::Ready {
            self.call_raw(req)
        } else {
            let err = io::Error::new(io::ErrorKind::Other, "Invalid state");
            let f = future::err(err);
            FutureResponse(Box::new(f))
        }
    }
    /// Make a call. This call doesn't take care of handshake and session;
    /// regeneration.
    fn call_raw(&self, req: Frame) -> FutureResponse;
```

In this scenario I only need to mock `call_raw` and `connection_state` methods, but right now it's not possible...

**Comment by la10736** [comment]
I guess that there is no way to change what `derive` should to mock and what not. In this cases you should use `mock!` macro instead.

**Comment by kriomant** [comment]
In fact, `#[derive(Mock)]` and `mock!` are no different and generate almost the same code.

I would just skip trait methods with body. But it is strange that you don't bother which exactly method will be called by code under check. If code being checked calls `call`, wouldn't you expect exactly it, and not `call_raw`?

And it may be dangerous too, right now mock objects are totally dull - the do nothing until you tell them to do it using expectations. And if I leave default methods as is, they may do different strange things - open files, allocate memory, etc.

So, while it is technically possible to skip default trait methods, I want to know more details of you specific scenario.

**Comment by kriomant** [comment]
@la10736 Sorry, you are right, using `mock!` you may just omit declaration of default methods.

**Comment by kriomant** [comment]
@andoriyu Just to be clear. You can do what you want right now using:

```rust
// No derive here
pub trait Engine {
    fn connection_state(&self) -> ConnectionState;
    fn generate_session(&self) -> Session { ... }
    fn call(&self, req: Frame) -> FutureResponse { ... }
    fn call_raw(&self, req: Frame) -> FutureResponse;
}

mock! {
  EngineMock,
  self,
  trait Engine {
    fn connection_state(&self) -> ConnectionState;
    fn call_raw(&self, req: Frame) -> FutureResponse;
  }
}

#[test]
fn test() {
  let scenario = Scenario::new();
  let mock = scenario.create_mock::<EngineMock>();
}
```

Is it sufficient for your needs?

**Comment by andoriyu** [comment]
@kriomant Yes, this will do. Well the way I did it is moved methods with default implementation into separate trait and made blanket implementation for anything that implement original trait. 

The idea is you implement a few methods and get tons of free sugar and test was for that free sugar.
