### ISSUE TITLE
 the trait bound `&'static serial::SerialPort: mockers::Mocked` is not satisfied

### ISSUE THREAD

**Issue by shortwavedave** [kriomant/mockers#16]
I was trying to use this with serial-rs and nightly and got the following error:

> error[E0277]: the trait bound `&'static serial::SerialPort: mockers::Mocked` is not satisfied
>    --> src/stalker_radar.rs:383:33
>     |
> 383 |         let mut cond = scenario.create_mock_for::<SerialPort>();
>     |                                 ^^^^^^^^^^^^^^^ the trait `mockers::Mocked` is not implemented for `&'static serial::SerialPort`

Any ideas?

**Comment by kriomant** [comment]
Which way you used to generate mock? Provide corresponding code, please.

Supposing you used `mock!` macro and not `#[derive(Mock)]`, you should use `scenario.create_mock::<MockName>()` instead of `scenario.create_mock_for::<TraitName>()`.

**Comment by kriomant** [comment]
@shortwavedave, is your problem solved?
