### ISSUE TITLE
`and_call_clone` doesn't work if the result type is not `Clone`

### ISSUE THREAD

**Issue by chriscoomber** [kriomant/mockers#17]
See https://github.com/kriomant/mockers/blob/d27a30da541e21a9ce06fc6e684cab894e435333/doc/guide.md#expecting-several-calls from the guide:

> Thus, there are additional methods on call matchers: and_return_clone and and_call_clone. They are available only when the result type is clonable (or the closure is FnMut).

This seems to imply that if the closure is `FnMut`, then you don't need the result type to be clone. This matches with the actual implementation https://github.com/kriomant/mockers/blob/fd6783ac3ccca92a4306f0ddb16f142a282c1732/mockers/src/lib.rs#L218: 

```rust
    pub fn and_return_clone(self, result: Res) -> Reaction0<Res> {
        Reaction0 { call_match: self, action: Rc::new(RefCell::new(move || result.clone())) }
    }

    pub fn and_call_clone<F>(self, func: F) -> Reaction0<Res>
            where F: FnMut() -> Res + 'static {
        Reaction0 { call_match: self, action: Rc::new(RefCell::new(func)) }
```

In `and_call_clone`, the `Res` is not cloned. However, this doesn't actually work as this is all within:

```rust
impl<Res: Clone + 'static> CallMatch0<Res> {
    ....
}
```

So `Res` needs to be clone, even though that isn't technically required.

I think the fix is just to split these two method definitions into separate `impl`s with more relaxed conditions on `Res` for the impl of `and_call_clone`.

Edit: scenario where this issue raises its ugly head:

```rust
let mock = scenario.create_mock_for::<MyTrait>();
scenario.expect(mock.foo_call().and_call_clone(|| Box::new(futures::ok(3))));
```

which is required by the relatively common API

```rust
trait MyTrait {
    fn foo() -> Box<Future<i32, ()>>;
}
```

(or indeed any API where the return type is not `Clone`).

**Comment by kriomant** [comment]
Thanks for spotting this. I've fixed it the way you proposed.
