### ISSUE TITLE
Feature request: mock objects implement `Clone`

### ISSUE THREAD

**Issue by chriscoomber** [kriomant/mockers#19]
# Issue

My function under test might look like:

```rust
fn foo<T: Combobulator + Clone + Debug + 'static>(input: i32,  combobulator: T) -> Result<i32, ()> {
    ...
}
```

Right now, if I create a mock using `mockers`:

```rust
let combobulator_mock = scenario.create_mock_for::<Combobulator>();
let res = foo(3, combobulator_mock); // Doesn't compile as `Combobulator` doesn't implement `Clone`
```

# Can we work around, without changes to `mockers`?

I can't work around this by putting it inside an `Rc`:

```rust
let combobulator_mock = Rc::new(scenario.create_mock_for::<Combobulator>());
let res = foo(3, combobulator_mock); // Doesn't compile as `Rc<Combobulator>` doesn't implement `Combobulator` - though it does implement `Deref<Target=Combobulator>`
```

So the only way to work around this is something like

```rust
#[derive(Clone)]
struct CloneableCombobulatorMock(CombobulatorMock);

impl Combobulator for CloneableCombobulatorMock {
    fn combobulate(&self) {
        self.0.combobulate()
    }
}
```

which is pretty tedious with large traits. It would be nice if this code was generated.

# Suggested change to `mockers`

I think it would be nice if the mock object created by `create_mock_for` implemented `Clone` already. Moreover, we could implement `Send` and `Sync` too, to head off similar issues. One way to do this is to wrap the current mock in an `Arc<Mutex<_>>`. E.g. generate code similar to:

```rust
/// This is the mock produced by `create_mock_for`
#[derive(Clone, Debug)]
struct MockCombobulator(Arc<Mutex<MockCombobulatorInner>>);

/// This is basically what `create_mock_for` used to create. It actually has all the logic.
struct MockCombobulatorInner {
    ....
}

impl Combobulator for MockCombobulator {
    fn combobulate(&self) {
        self.lock().combobulate()
    }
}
```

I think this is justifiable:
- `Arc`s disadvantages are possible reference loops (which we haven't introduced in the above code) and performance costs (which aren't important for mocks)
- `Mutex`s disadvantages are possible deadlocks in multithreaded code

**Comment by kriomant** [comment]
While it is tecnhically simple to do so, it doesn't seem right to me. When you clone object, you get separate instance, and I wouldn't expect that these two instances share expectations. And if you don't share expectation, there is no way to set expectations for new instance.

So I propose exposing scenario reference from mock objects. This will allow you to implement `Clone` itself:

```rust
impl Clone for AMock {
    fn clone(&self) -> AMock {
        let scenario = self.scenario_handle();
        let cloned = scenario.create_mock_for::<A>();
        scenario.expect(cloned.foo_call(ANY).and_return_default().times(1));
        cloned
    }
}
```

However, it may be also useful to
  * check number of `clone` calls
  * do different actions on cloning in different cases.

So I also propose adding separate macro (or option for existing one) which allows you to mock `clone` method. It should look like this:

```rust
#[derive(Mock)]
trait A { fn foo(&self); }

mock_clone!(AMock);

let scenario = Scenario::new();
let mock = scenario::create_mock_for::<A>();
scenario.expect(mock.clone_call().and_call({
    let scenario = scenario.handle();
    move || {
        let item = scenario.create_mock_for::<A>();
        scenario.expect(item.foo_call().and_return(()));
        item
    }
}));
```

What do you think about it?

**Comment by chriscoomber** [comment]
So in my particular use-case, I'm trying to mock out something which has shared state. In particular, I've got a HTTP client implementing an API trait, and cloning the client actually just produces another handle to the underlying resources. When mocking out the API trait, I'd like it for all clones of the client to share their expectations, because they are all logically talking to the same server.

Anyway, I appreciate if that's not universally what we'd want `Clone` to look like in `mockers`, and it is possible to work my issue by making my function under test take a `T: AsRef<A>`:

```rust
trait A {
  fn foo();
}

fn function_under_test<T: AsRef<A> + Clone>(a: T) { ... }

#[test]
fn test_function_under_test() {
    #[derive(Clone)]
    struct CloneMockA(Arc<AMock>);
    impl AsRef<A> for CloneMockA {
        fn as_ref(&self) -> &A {
            &self.0
        }
    }
    let scenario = Scenario::new();
    let mock = scenario::create_mock_for::<A>();
    scenario.expect(mock.foo_call().and_return(()));
    let clone_mock = CloneMockA(Arc::new(mock));

    function_under_test(clone_mock);
}
```

You proposal sounds sensible to me. I wonder if there's a way to solve both issues?

**Comment by kriomant** [comment]
I've implemented mock cloning. It's a bit hacky, but should do the work.
You case is covered by `mock_clone!(AMock, share_expectations);`.
