### ISSUE TITLE
error[E0244]: wrong number of type arguments: expected 1, found 2

### ISSUE THREAD

**Issue by da2018** [kriomant/mockers#31]
```rust
#[cfg_attr(test, derive_mock)]
pub trait RequestHandler {
    fn agent(&self) -> Agent;
    fn get(&self, path: String, timeout: u64) -> Result<Response>;
    fn put(&self, path: String, data: Option<String>) -> Result<Response>;
}

```

error[E0244]: wrong number of type arguments: expected 1, found 2
  --> src/api/client.rs:36:18
   |
36 | #[cfg_attr(test, derive_mock)]
   |                  ^^^^^^^^^^^^ expected 1 type argument

By the way, could you provide more comprehensive document or usage? How does this library work with struct?

The [User guide](https://github.com/kriomant/mockers/blob/master/doc/guide.md) doesn't work.

**Comment by da2018** [comment]
By the way, could you provide more comprehensive document? 

The [User guide](https://github.com/kriomant/mockers/blob/master/doc/guide.md) doesn't work

**Comment by la10736** [comment]
Sorry... but where do you read about to use `#[cfg_attr(test, derive_mock)]`. `cfg_attr` take just one argument.

I guess you would write something like 

```rust
#[derive_mock]
pub trait RequestHandler {
    fn agent(&self) -> Agent;
    fn get(&self, path: String, timeout: u64) -> Result;
    fn put(&self, path: String, data: Option) -> Result;
}
```
that will create your mock struct just for tests.

**Comment by kriomant** [comment]
Seems like code generated by macro conflicts with your `Option` and `Result` types. Can you provide their definitions?

**Comment by da2018** [comment]
```
use std::result;

pub type Result<T> = result::Result<T, Error>;
```

**Comment by kriomant** [comment]
If you `Result` requires one type parameter, why is it used in trait definition without any type argument? Same question for `Option`.

**Comment by da2018** [comment]
@kriomant  My bad, I just `quote`  my code, so the <Response> is hidden as html label. 😂

**Comment by kriomant** [comment]
Ok, now I see. I'm in process of reproducing this issue. Please hold. Your issue is very important to us :-)

**Comment by da2018** [comment]
Ok, waiting for it, also could you provide more example or usage and more comprehensive document?

**Comment by kriomant** [comment]
Fixed in 0.11.2

**Comment by kriomant** [comment]
Please describe more throughout what is missing from documentation

**Comment by da2018** [comment]
Cool, `wrong number` has been resolved.

Another question is the User guide and README usage are different, and it seems that `#[derive_mock]` can not work for latest version ? It confuses me a lot.

By the way, could you provide some examples about mocker working with `struct`?

e.g. 

```rust
#![feature(proc_macro)]
#[cfg(test)] extern crate mockers;
#[cfg(test)] extern crate mockers_derive;

#[cfg(test)] use mockers_derive::derive_mock;


#[cfg_attr(test, derive_mock)]
pub trait AirConditioner {
    fn make_hotter(&mut self, by: i16);
    fn make_cooler(&mut self, by: i16);
    fn get_temperature(&self) -> i16;
    fn set_temperature_20(&mut self);
}

pub struct Test{
    pub temperature:i16,
}

impl AirConditioner for Test{
    fn make_hotter(&mut self, by: i16) {self.temperature += by;}
    fn make_cooler(&mut self, by: i16) {self.temperature -= by;}
    fn get_temperature(&self) -> i16 {self.temperature}
    fn set_temperature_20(&mut self){
        let t = self.get_temperature();
        if t < 20 {
            self.make_hotter(20);
        } else {
            self.make_cooler(20);
        }
    }
}


#[cfg(test)]
mod test {
  use super::*;
  use mockers::Scenario;

  #[test]
  fn test_set_temperature_20() {
      let mut t = Test{temperature:1};
      let scenario = Scenario::new();
      let mut cond = scenario.create_mock_for::<AirConditioner>();


      scenario.expect(cond.get_temperature_call().and_return(233));

      t.set_temperature_20();
      println!("{}",t.temperature);
  }
}
```
