### ISSUE TITLE
.times() can't be used with .and_call()

### ISSUE THREAD

**Issue by asomers** [kriomant/mockers#32]
`.times()` can be used on an Expectation to require that it be called a specific number or range of times.  It works if the expectation was created with `.and_return_clone` but not `.and_call`.  Here's an example:
```rust
#[derive_mock]
pub trait A {
    fn foo(&self);
}

let scenario = Scenario::new();
let mock = scenario.create_mock_for::<A>();
scenario.expect(mock.foo_call().and_call(|| ()).times(2));
//scenario.expect(mock.foo_call().and_return_clone(()).times(2));
mock.foo();
mock.foo();
```
```
error[E0599]: no method named `times` found for type `mockers::Expectation0<()>` in the current scope
   --> src/t_mockers.rs:457:57
    |
457 |         scenario.expect(mock.foo_call().and_call(|| ()).times(2));
    |                                                         ^^^^^

error: aborting due to previous error
```

**Comment by kriomant** [comment]
You can use `and_call_clone(|| ())`. Yeah, I know, name is misleading.

**Comment by asomers** [comment]
Huh.  I understand why there's a difference between `and_return` and `and_return_clone`.  But why is there a need for `and_call_clone`?  Doesn't it construct a new value on every call?

**Comment by kriomant** [comment]
Both `and_return` and `and_return_clone` moves their argument, but `and_return` accepts `FnOnce`, while `and_return_clone` accepts `FnMut`.
