### ISSUE TITLE
support mocking traits with static methods

### ISSUE THREAD

**Issue by asomers** [kriomant/mockers#38]
It's fairly common for a trait to have static methods, especially for constructors.  Unfortunately, mockers will panic if you attempt to mock such a trait, even if the static method is never called.  Could you please add support for mocking traits with static methods?  Even if the static method itself can't be mocked, this would still be useful.  Example:
```rust
trait MyTrait {
    fn create() -> Self where Self: Sized;
    fn foo(&self);
}
#[cfg(test)]
mod t {
    use mockers::*;
    use mockers_derive::*;
    use super::*;

    mock!{
        MockMyTrait,
        self,
        trait MyTrait {
            fn create() -> Self where Self: Sized;
            fn foo(&self);
        }
    }

    #[test]
    fn t() {
        let s = Scenario::new();
        let mock = s.create_mock::<MockMyTrait>();
        mock.foo_call();
        mock.foo();
    }
}
```
```
error: proc macro panicked
  --> src/lib.rs:12:5
   |
12 | /     mock!{
13 | |         MockMyTrait,
14 | |         self,
15 | |         trait MyTrait {
...  |
18 | |         }
19 | |     }
   | |_____^
   |
   = help: message: Methods without `self` parameter are not supported

error: aborting due to previous error

error: Could not compile `mockers_static_methods`.
```

**Comment by kriomant** [comment]
Fixed in 0.13.0

Syntax will probably be improved, but at least it works.

**Comment by asomers** [comment]
Cool!  Are there limitations on the kinds of expectations you can set on static methods?

**Comment by kriomant** [comment]
The only limitation is that only one scenario may mock static methods of given trait at any moment, so be careful, because by default tests are running in several threads. Otherwise, static method mocks are as powerful as ordinary ones.

**Comment by asomers** [comment]
Ok.  BTW, please push the new 0.13.0 code into Github.

**Comment by kriomant** [comment]
Done
