### ISSUE TITLE
Mock not working when function takes Box<Self>

### ISSUE THREAD

**Issue by ChrisGreenaway** [kriomant/mockers#50]
```
pub trait A {
}

pub trait B {
  fn into_a(self: Box<Self>) -> Box<dyn A>
}
```

when calling `create_mock_for::<dyn B>()`, I get:
```
the trait bound `&'static dyn B: mockers::Mocked` is not satisfied ... the trait `mockers::Mocked` is not implemented for `&'static dyn B`
```

Looks like the macro misses out:
```
impl ::mockers::Mocked for &'static dyn B {
    type MockImpl = BMock;
}
```

because if I add that in by hand it works OK.

**Comment by ChrisGreenaway** [comment]
The into_a method is also missing from the mock handle object.

**Comment by ChrisGreenaway** [comment]
If nothing else, this is caused by the `self: Box<Self>` which isn't detected in the `is_static` check in `generate_trait_methods`: `Some(FnArg::SelfRef(..)) | Some(FnArg::SelfValue(..))`

**Comment by ChrisGreenaway** [comment]
@kriomant - thank you very much!

**Comment by kriomant** [comment]
You're welcome. I'm happy that someone tries to use my library :-)
