### ISSUE TITLE
Matchers with Strings unergonomic

### ISSUE THREAD

**Issue by ChrisGreenaway** [kriomant/mockers#53]
If I want to mock a method that accepts a String argument, then I cannot use &str matchers, I have to use a String matcher. For example, a method on a trait such as:
```
do_something(String value);
```
I have to write:
```
handle.do_something(eq(String::from("expected")))
```
whereas I would expect to be able to write:
```
handle.do_something(eq("expected"))
```
If I don't get this right, I get the error:
```
the trait `mockers::MatchArg<std::string::String>` is not implemented for `mockers::matchers::EqMatchArg<&str>`
```

**Comment by kriomant** [comment]
Now you can use

```rust
handle.do_something("expected")
```

**Comment by ChrisGreenaway** [comment]
@kriomant - thanks, but that doesn't really fix the issue, because it doesn't work with the eq() matcher (and other related simple matchers). In other words, if the test had:
```
scenario.expect(handle.foo(eq("bla")).and_return(()));
```
rather than
```
scenario.expect(handle.foo("bla").and_return(()));
```
then that it still doesn't work. It's not just the eq matcher, it's the other simple matchers (such as lt).
