### ISSUE TITLE
Cannot derive multi argument method's trait 

### ISSUE THREAD

**Issue by la10736** [kriomant/mockers#6]
First of all thanks for this wonderful job! ... And please apologize me if I cannot write a fix : I'm just a Rust newbie. 

Seams that is impossible to create a mock for a trait that define methods with more than one arguments:

I changed `test/derive.rs` by add two more test like

```rust
#[derive(Mock)]
pub trait TraitWithJustOneArg {
    fn foo(&self, first: i32);
}

#[derive(Mock)]
pub trait TraitWithMoreThanOneArg {
    fn foo(&self, first: i32, second: i32);
}

#[test]
fn test_trait_that_define_a_one_parameter_signature_function() {
    let mut scenario = Scenario::new();
    let _mock = scenario.create_mock_for::<TraitWithJustOneArg>();
}

#[test]
fn test_trait_that_define_a_two_parameters_signature_function() {
    let mut scenario = Scenario::new();
    let _mock = scenario.create_mock_for::<TraitWithMoreThanOneArg>();
}
```
 When I try to compile it I receive follow error:

```
error: expected token: `,`
  --> tests/lib.rs:26:1
   |
26 | mock!{
   | ^ in this macro invocation
   |
   = note: this error originates in a macro outside of the current crate
```
After a bunch `println!` I found that the problem is in  [format invocation](../tree/master/mockers_macros/src/lib.rs#L494) where `$args_tuple_fields` become something like `_args_ref.0 _args_ref.1` without any comma. I spend some hours to try to fix it but I'm cannot understad how to use `syntax::ext::base::ExtCtxt` to build the correct expansion.

Moreover I replace it by `format!("ERROR")` and obviously 5 test fail because the expected exception doesn't match but I can derive multiargs methods a follow tests will pass correctly:

```rust
#[derive(Mock)]
pub trait A {
    fn more_args(&self, arg1 : i32, arg2: i32) -> i32;
}


#[test]
fn test_more_than_one_args() {
    let mut scenario = Scenario::new();
    let mock = scenario.create_mock_for::<A>();

    scenario.expect(mock.more_args_call(1, 2).and_return_default().times(1));

    assert_eq!(mock.more_args(1, 2), 0);
}

#[test]
#[should_panic(expected="unexpected call to `A#0.more_args(ERROR)`")]
fn test_more_than_one_args_should_fail_values_doesnt_match() {
    let mut scenario = Scenario::new();
    let mock = scenario.create_mock_for::<A>();

    scenario.expect(mock.more_args_call(1, 3).and_return_default().times(1));

    assert_eq!(mock.more_args(1, 2), 0);
}
```

I hope that you can find a better solution than my hack.

**Comment by kriomant** [comment]
Thanks for noticing this stupid error, I've fixed it.
