### ISSUE TITLE
Derive custom traits is deprecated

### ISSUE THREAD

**Issue by la10736** [kriomant/mockers#9]
Form the recents rust update I know that derive from custom trait is deprecated and will be removed in `1.15` rust version:

```
warning: `#[derive]` for custom traits is deprecated and will be removed in v1.15. Prefer using procedural macro custom derive
   --> /home/mdamico/git/ivs.3980/shared/ivsrepo/src/insert_liu_tree.rs:164:10
```

Regards

**Comment by kriomant** [comment]
Sadly, procedural macro custom derive doesn't support `derive` for traits.
So you will have to use `mock!` syntax as [described in user guide](https://github.com/kriomant/mockers/blob/master/doc/guide.md#usage-from-test-crate).
I will update docs as soon as current derive implementation is removed.

**Comment by la10736** [comment]
That's very drawback.. It'll lead to lot of code duplication.

I'm starting to thing that to much things fight against mocking in *rust*. I wrote a project by use test double and mocking and that was not a great experience ...

**Comment by kriomant** [comment]
You can also use code generation. It will work while `syntex` supports it.
And if you have some hard problem with mocking, show me, maybe we can solve it.

**Comment by kriomant** [comment]
I just added support for procedural macros. You may use it instead of compiler plugin. Procedural macros are nighly feature, but it is intended to be stabilized soon. See `air_proc_macro` example for details.

**Comment by la10736** [comment]
Thx!!! I saw your work in progress yesterday. I'll try procedural macro approach as soon as possible.

Yesterday I try to update my project to nightly and mockers 0.6.1 but maybe there is a regression on `mock!` macro approach. That was not my real goal and then I come back to 0.5.7 but I'll return on it and if I find this issue again I'll file a new issue.

Thx again.
